### ISSUE TITLE
Assassination Rogue Roation

### ISSUE THREAD

**Issue by phantom1004** [darhanger/PQR_DarhangeR_3.3.5a#1]
Tried out the profile for Assassination rogue, and then spent an hour and a half trying to modify the code with no victory, so making a Bug Report.

Simple thing, it doesn't use envenom, like atall! it will just stockpile 5CP and then wait till 2 seconds is left on snd and then refresh snd.

If you need anymore info let me know

**Comment by darhanger** [comment]
Fix it!
