### ISSUE TITLE
Warlock Rotation Not Working

### ISSUE THREAD

**Issue by Fot3k** [darhanger/PQR_DarhangeR_3.3.5a#4]
When you enable the warlock rotation, it asks to click on an item in the chat window. I do this but nothing happens and other spells will not cast. Debug mode shows it trying to cast spellstone and other self casts, so I tried removing these from the rotation but then it won't cast damage spells either. Keeps making a noise like it's trying to cast something but it can't. Much appreciate your help. Thanks.

**Comment by darhanger** [comment]
Problem on your side
